version: '3'  # version of compose format 

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
      #./build_model.py  # path is relative to docker-compose.yml localtion
    volumes:
      - ./lib:/app/lib # mount point
#    environment:
#      FLASK_APP: app.py
    ports:
      - "80:5000"  # host:container
    entrypoint:
      - python
